config/routes.rb
Rails.application.routes.draw do

  namespace :admin do
    resources :customers, only: [ :index, :show, :edit, :update]
  end

  scope module: :customer do
    resource :customers, only: [ :show, :edit, :update] do
      member do
        patch 'stateupdate'
        get 'exit'
        put "/customers/:id/hide" => "customers#hide", as: 'customers_hide'
      end
    end
  end

  namespace :admin do
    resources :genres, only: [:create, :index, :edit, :update]
  end

  scope module: :customer do
    resources :items, only: [:show, :index]
  end

  namespace :admin do
    resources :items, only: [ :index, :show, :new, :create, :edit, :update]
  end

  scope module: :customer do
      resource :orders, except: [:show] do
        get 'put'
        post 'confirm'
        get 'complete'
    end
    resources :orders, only: [ :index, :show, :create]
  end

  namespace :admin do
    resources :orders, only: [ :index, :show, :update]
  end

  namespace :admin do
    resources :orderd_items, only: [:update]
  end

  scope module: :customer do
    resources :cart_items, only: [:index, :create, :destroy, :update] do
      member do
        delete 'alldestroy'
      end
    end
  end

  scope module: :customer do
    resources :shippings, only: [:create, :destroy, :edit, :update, :index]
  end

  namespace :admin do
    root to: 'homes#top'
  end

  scope module: :customer do
    root to: 'homes#top'
    get 'home/about' => 'homes#about'
  end

      devise_for :admins, controllers: {
    sessions:      'admins/sessions',
    passwords:     'admins/passwords',
    registrations: 'admins/registrations'
  }
  devise_for :customers, controllers: {
    sessions:      'customers/sessions',
    passwords:     'customers/passwords',
    registrations: 'customers/registrations'
  }



end

app/models/customer.rb
class Customer < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  validates :last_name, presence: true
  validates :first_name, presence: true
  validates :kana_last_name, presence: true
  validates :kana_first_name, presence: true
  validates :post_code, presence: true
  validates :post_code, length: { is: 7 }
  validates :address, presence: true
  validates :telephone_number, presence: true

  def update_without_current_password(params, *options)
    params.delete(:current_password)

    if params[:password].blank? && params[:password_confirmation].blank?
      params.delete(:password)
      params.delete(:password_confirmation)
    end

    result = update_attributes(params, *options)
    clean_up_passwords
    result
  end
  has_many :orders, dependent: :destroy
  has_many :cart_items, dependent: :destroy
  has_many :shippings, dependent: :destroy

  def active_for_authentication?
    super && (self.member_state == true)
  end

end

app/models/order.rb
class Order < ApplicationRecord
  belongs_to :customer
  has_many :orderd_items, dependent: :destroy

  enum payment_method:[:"クレジットカード", :"銀行振込"]
  enum address_method:[:"ご自身の住所", :"登録済みの住所から選択", :"新しいお届け先"]
  enum state: {"入金待ち": 0, "入金確認": 1, "製作中": 2, "発送準備中": 3, "発送済み": 4}

  # admin/order/showの制作ステータス更新のために記述
  accepts_nested_attributes_for :orderd_items

  validates :post_code, presence: true
  validates :post_code, length:{ is: 7 }
  validates :address, presence: true
  validates :name, presence: true

end

app/controllers/admin/customers_controller.rb
class Admin::CustomersController < ApplicationController

  def index
    @customers = Customer.page(params[:page]).per(10)
  end

  def show
    @customer = Customer.find(params[:id])
  end

  def edit
    @customer = Customer.find(params[:id])
  end

  def update
   @customer = Customer.find(params[:id])
   if @customer.update(customer_params)
    flash[:notice] = "You have updated book successfully."
    redirect_to admin_customer_path(@customer.id)
   else
     render :edit
   end
  end

  private

  def customer_params
    params.require(:customer).permit(:last_name,:first_name, :kana_last_name, :kana_first_name, :post_code, :address, :telephone_number,:telephone_number, :email, :member_state)
  end

end

app/controllers/admin/orders_controller.rb
class Admin::OrdersController < ApplicationController
  before_action :authenticate_admin!

  def index
    @orders = Order.all
    @orderd_items = OrderdItem.where(order_id: params[:id])
  end

  def show
		@order = Order.find(params[:id])
    #show.html内でorderd_item(中間テーブル)を呼び出すために使用する
		@orderd_items = OrderdItem.where(order_id: params[:id])
  end

  def update
    @order = Order.find(params[:id])
    @order.update(order_params)
    redirect_back(fallback_location: root_path)
  end

  private
  # show.htmlにてorderd_itemの制作ステータスを更新できるようにするため、rderd_item_attributes: [:create_state] を記述しています
  def order_params
    params.require(:order).permit(:state, orderd_item_attributes:[:id, :create_state])
  end
end

app/controllers/customer/cart_items_controller.rb
class Customer::CartItemsController < ApplicationController
  before_action :authenticate_customer!

  def index
    @cart_items = current_customer.cart_items
  end

  def create
    @cart_item = CartItem.new(cart_item_params)
    @cart_item.customer_id = current_customer.id
    if @cart_item.save
     redirect_to cart_items_path
    else
     redirect_back(fallback_location: root_path)
    end
  
  end

  def update
    @cart_item = CartItem.find(params[:id])
    @cart_item.update(cart_item_params)
    redirect_to cart_items_path
  end

  def destroy
    @cart_item = CartItem.find(params[:id])
    @cart_item.destroy
    redirect_to cart_items_path
  end

  def alldestroy
    CartItem.destroy_all
    redirect_to cart_items_path
  end

  private

  def cart_item_params
    params.require(:cart_item).permit(:customer_id, :item_id, :amount)
  end
end

app/controllers/customer/customers_controller.rb
class Customer::CustomersController < ApplicationController


  def show
    @customer = current_customer
  end

  def edit
    @customer = current_customer
  end

  def update
    @customer = current_customer
    if @customer.update(customer_params)
     flash[:notice] = "You have updated user successfully."
     redirect_to customers_path
    else
     render :edit
    end
  end

  def exit
    @customer = current_customer
  end

  def hide
    @customer = current_customer
    @customer.update(member_state: false)
    reset_session
    flash[:notice] = "ありがとうございました。またのご利用を心よりお待ちしております。"
    redirect_to root_path
  end


  def active_for_authentication?
    super && (self.member_state == false)
  end

  private

def customer_params
    params.require(:customer).permit(:last_name,:first_name, :kana_last_name, :kana_first_name, :post_code, :address, :telephone_number,:telephone_number, :email)
end

end

app/controllers/customer/homes_controller.rb
class Customer::HomesController < ApplicationController

  def top
    @item = Item.where(sale_state: "true").limit(4).order(" created_at DESC ")
  end
end

app/controllers/customer/items_controller.rb
class Customer::ItemsController < ApplicationController
before_action :authenticate_customer!

  def show
    @item = Item.find(params[:id])
    @cart_item = CartItem.new
  end

  def index
    @items = Item.where(sale_state: "true").limit(8)
    @item = Item.all
    @item_page = Item.page(params[:page]).per(8)
  end
end

app/controllers/customer/orderd_items_controller.rb
class Admin::OrderdItemsController < ApplicationController
  def update
    @orderd_item = OrderdItem.find(params[:id])
    @order = @orderd_item.order
  end
end

app/controllers/customer/orders_controller.rb
class Customer::OrdersController < ApplicationController
  before_action :authenticate_customer!


  def show
    @order = Order.find(params[:id])
    @orderd_items = OrderdItem.where(order_id: params[:id])
    @cart_items = current_customer.cart_items
  end

  def index
    @orders = current_customer.orders

  end

  def put
    @customer = current_customer
    @order_address = current_customer.address
    @order = Order.new
  end

  def confirm
    params[:order][:payment_method] = params[:order][:payment_method].to_i
    @order = Order.new(order_params)

    if params[:order][:address_method] == "0"
      @order.post_code = current_customer.post_code
      @order.address = current_customer.address
      @order.name = current_customer.last_name+current_customer.first_name

    elsif  params[:order][:address_method] ==  "1"
      shipping = Shipping.find(params[:order][:shipping_id])
      @order.post_code = shipping.post_code
      @order.address = shipping.address
      @order.name = shipping.name

    elsif params[:order][:address] ==  "2"
      @order = Shipping.new()
      @order.post_code = params[:order][:post_code]
      @order.shipping_address = params[:order][:shipping_address]
      @order.name = params[:order][:name]
      @order.customer_id = current_customer.id

      if @address.save
      @order.post_code = @shipping_address.post_code
      @order.address = @shipping_address.address
      @order.name = @shipping_address.name

      else
        render 'put'
      end
    end
      @cart_items = CartItem.where(customer_id: current_customer.id)
      @total = 0
  end

    def complete
    end

    def create
      @order = Order.new(order_params)
      @order.customer_id = current_customer.id
      @CartItems = current_customer.cart_items

      if  @order.save
        #orderd_itemsの保存
        current_customer.cart_items.each do |cart_item|
          @orderd_item = OrderdItem.new
          @orderd_item.item_id = cart_item.item_id
          @orderd_item.quantity = cart_item.amount
          @orderd_item.price = (cart_item.item.non_tax_price * 1.1).floor
          @orderd_item.order_id = @order.id  #注文商品に注文idを紐付け
          @orderd_item.save  #注文商品を保存
        end
        current_customer.cart_items.destroy_all
        redirect_to complete_orders_path
      else
        flash[:alert] = "お届け先が正しく入力されていません。お届け先の入力をお願いします。"
        redirect_to  put_orders_path
      end
    end

    private
    def order_params
      params.require(:order).permit(:customer_id, :post_code, :address, :name, :billing_amount, :fee, :payment_method, :state )
    end
end

app/controllers/customer/shippings_controller.rb
class Customer::ShippingsController < ApplicationController


  def create
    @shippings = Shipping.all
    @shipping = Shipping.new(shipping_params)
    @shipping.customer_id = current_customer.id
    if @shipping.save
      flash[:notice] = "Shipping was successfully created"
      redirect_to shippings_path
    else
      render 'index'
    end
  end

  def index
    @shippings = Shipping.all
    @shipping = Shipping.new
    @shipping.customer_id = current_customer.id
  end

  def edit
    @shipping = Shipping.find(params[:id])
  end

  def update
    shipping = Shipping.find(params[:id])
    if shipping.update(shipping_params)
      flash[:notice] = "You have updated shipping successfully."
      redirect_to customers_path
    else
      render 'index'
    end
  end

  def destroy
    shipping = Shipping.find(params[:id])
    shipping.destroy
    redirect_to shippings_path
  end

  private
  def shipping_params
    params.require(:shipping).permit(:post_code, :address, :name)
  end

end

app/controllers/customers/confirmations_controller.rb
# frozen_string_literal: true

class Customers::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/customers/omniauth_callbacks_controller.rb
# frozen_string_literal: true

class Customers::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/heartcombo/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

app/controllers/customers/passwords_controller.rb
# frozen_string_literal: true

class Customers::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/customers/registrations_controller.rb
# frozen_string_literal: true

class Customers::RegistrationsController < Devise::RegistrationsController
  # before_action :configure_sign_up_params, only: [:create]
  before_action :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
  # def create
  #   super
  # end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_up_params
  #   devise_parameter_sanitizer.permit(:sign_up, keys: [:attribute])
  # end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.permit(:account_update, keys: [:attribute])
  # end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end

  def configure_account_update_params
    devise_parameter_sanitizer.permit(:account_update, keys: [:name])
  end

    #必須  更新（編集の反映）時にパスワード入力を省く
  def update_resource(resource, params)
    resource.update_without_password(params)
  end

  #任意  更新後のパスを指定
  def after_update_path_for(resource)
    customers_path(@customer.id)
  end

  def configure_account_update_params
    devise_parameter_sanitizer.permit(:account_update, keys: [:name])
  end


end

app/controllers/customers/sessions_controller.rb
# frozen_string_literal: true

class Customers::SessionsController < Devise::SessionsController
  #before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end

  def reject_customer
    @customer = Customer.find_by(email: params[:customer][:email].downcase)
    if @customer
      if (@customer.valid_password?(params[:customer][:password]) && (@customer.active_for_authentication? == false))
        flash[:error] = "退会済みです。"
        redirect_to new_customer_session_path
      end
    else
      flash[:error] = "必須項目を入力してください。"
    end
  end

end

app/controllers/customers/unlocks_controller.rb
# frozen_string_literal: true

class Customers::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/helpers/admin/customers_helper.rb
module Admin::CustomersHelper
end

app/helpers/admin/orders_helper.rb
module Admin::OrdersHelper
end

app/helpers/customer/cart_items_helper.rb
module Customer::CartItemsHelper
end

app/views/customer/orders/complete.html.erb
<div class="container-fluid">
  <div class="row">
    <div  class="position-absolute h-100 w-100 m-0 d-flex align-items-center justify-content-center h1">ご注⽂ありがとうございました！</div>
  </div>
</div>

app/views/customer/orders/confirm.html.erb
<div class="container m-5">
  <div class="row">
    <div class="col-2"></div>
    <h4 class="my-4 "><span style="background-color:#EFEFEF">　注文情報確認　</span></h4>
  </div>
  <div class="row">
    <table class='table col-8'>
      	   <thead class="table-active">
    		    <tr>
    			 <th>商品名</th>
    			 <th>単価(税込)</th>
    			 <th>数量</th>
    			 <th>小計</th>
    		     </tr>
    	   </thead>
    	   <tbody>
    	       <% tax = 1.1 %>
    	       <% @sum = 0 %>
    	 <%= form_for @order, :url => {action:"create"} do |f| %>
      	       <% @cart_items.each do |cart| %>
      		  <tr>
      		     <td>
      		         <%= attachment_image_tag cart.item, :image, :fill, 60, 60, format:'jpeg', fallback: "no_image.jpg", size:'60x60' %>
      		         <%= cart.item.title %>
      		     </td>
      		     <td>¥<%= (cart.item.non_tax_price * tax).floor %></td>
      		     <td><%= cart.amount %>個</td>
      		     <td>¥<%= (cart.amount * cart.item.non_tax_price * tax).floor %></td>
              </tr>
              <% @sum += (cart.amount * cart.item.non_tax_price * tax).floor %>
              <% end %>
           <tbody>
    </table>
    <% @Fee = 800 %>
    <div class="my-box col-auto"></div>
    <table class='table table-bordered col-3'>
                <tr>
                    <th class="table-active">送料</th>
                    <td>¥<%= @Fee %></td>
                </tr>
                <tr>
                    <th class="table-active">商品合計</th>
                    <td>¥<%= @sum %></td>
                </tr>
                <tr>
                    <th class="table-active">請求金額</th>
                    <td>¥<%= @sum + @Fee %></td>
                </tr>
       </table>
    </div>
    <table>
        <tbody>
            <tr>
                <td  style="width:25%" class="py-5" >支払い方法</td>
                <td class="py-5"><%= @order.payment_method %></td>
                <td></td>
            </tr>
            <tr>
                <td class="pb-5">お届け先</td>
                <td colspan="2" class="pb-5"><%= @order.post_code %> <%= @order.address %> <%= @order.name %>
                <!--orderのカラムにそれぞれ値を入れる-->
                 <%= f.hidden_field :customer_id, :value => current_customer.id %>
                 <%= f.hidden_field :name, :value => @order.name %>
                 <%= f.hidden_field :post_code, :value => @order.post_code %>
                 <%= f.hidden_field :address, :value => @order.address %>
                 <%= f.hidden_field :billing_amount, :value => @sum + @Fee %>
                 <%= f.hidden_field :fee, :value => @Fee %>
                 <%= f.hidden_field :payment_method, :value => @order.payment_method %></td>
            </tr>
            <tr>
                <td></td>
                <td></td>
                <td><%= f.submit '注文を確定する', class: "btn btn-xs btn-success" %></td>
            </tr>
        </tbody>
    </table>

    <% end %>

app/views/customer/orders/index.html.erb
<div class="container m-5">
  <div class="row">
    <div class="col-1"></div>
    <h4 class="my-4"><span style="background-color:#EFEFEF">　注文履歴一覧　</span></h4>
  </div>

    <div class="container index-container">
        <table class="table table-bordered">
            <thead class="thead-light">
                <tr>
                    <th>注文日</th>
                    <th>配送先</th>
                    <th>注文商品</th>
                    <th>支払金額</th>
                    <th>ステータス</th>
                    <th>注文詳細</th>
                </tr>
            </thead>
            <tbody>

            <% @orders.each do |order| %>
              <tr>
                <td><%= order.created_at.strftime('%Y/%m/%d') %></td>
                <td>〒<%= order.post_code %><br>
                 <%= order.address %><br>
                 <%= order.name %>
                </td>
                <td><% order.orderd_items.each do |orderd_item| %>
                      <%= orderd_item.item.title %><br>
                    <% end %>
                </td>
                <td><%= order.billing_amount.to_s(:delimited) %></td>

　　　　<!--参考：計算式を使った書き方-->
            <%# @sum = 0 %>
            <%# order.orderd_items.each do |orderd_item| %>
                <!--１つの商品の価格×数量を計算-->
                <%# @x = orderd_item.price * orderd_item.quantity %>
                <!--eachの数だけ@sumに足していく-->
                <%# @sum += @x %>
            <%# end %>
                <%# @total = @sum +800 %>
                <%#= @total.to_s(:delimited) %>

                <td><%= order.state %></td>

                <td><%= link_to "表示する", order_path(order), class: 'btn btn-primary' %></td>
              </tr>
            <% end %>
            </tbody>
        </table>
    </div>
</div>

app/views/customer/orders/put.html.erb
<div class="container m-5">
  <div class="row">
    <div class="col-2"></div>
    <h4 class="my-4 "><span style="background-color:#EFEFEF">　注文情報入力　</span></h4>
  </div>
     <% render 'layouts/errors',obj: @order %>
     <%= form_with model: @order, url: confirm_orders_path do |f| %>
     <h5>支払方法</h5>
     <div class="row">
      <span class="col-1"></span>
      <label>
       <%= f.radio_button :payment_method, 0, required: true %>クレジットカード
      </label>
     </div>
     <div class="row mb-1">
      <span class="col-1"></span>
        <label>
         <%= f.radio_button :payment_method, 1, required: true %>銀行振込
        </label>
     </div>

     <h5>お届け先</h5>
     <div class="row">
      <span class="col-1"></span>
      <label>
       <div>
        <%= f.radio_button :address_method, 0, checked: true %>
        <%= f.label(:address_method, "ご自身の住所") %>
        <p class="ml-3">
         <%= @customer.post_code %>
         <%= @customer.address %>
          <br>
          <%= @customer.last_name + @customer.first_name %>
         </p>
        </div>
     </div>
     <div class="row">
      <span class="col-1"></span>
      <div>
       <%= f.radio_button :address_method, 1 %>
       <%= f.label(:address_method, "登録済住所から選択") %>
       <p class="ml-3"><%= f.collection_select :shipping_id, Shipping.all, :id, :full_shipping %></p>
      </div>
     </div>
     <div class="row">
      <span class="col-1"></span>
       <div>
          <%= f.radio_button :address_method, 2 %>
          <%= f.label(:address_method, "新しいお届け先") %>
       </div>
     </div>
     <div class="row">
      <span class="col-1"></span>
       <table class="table col-7 table-sm table-borderless">
       <tr>
        <td style="width: 40%">郵便番号(ハイフンなし)</td>
        <td><%= f.text_field :post_code, placeholder: "郵便番号を入力する"%></td>
        <td></td>
       </tr>
       <tr>
        <td>住所</td>
        <td colspan="2"><%= f.text_field :address, placeholder: "住所を入力する"%></td>
       </tr>
       <tr>
        <td>宛名</td>
        <td><%= f.text_field :name, placeholder: "宛名を入力する"%></td>
        <td></td>
       </tr>
      </table>
    </div>
    <div class="row">
     <div class="col text-center">
    	 <%= f.submit "確認画面へ進む", class:"btn btn-primary" %>
      <% end %>
     </div>
    </div>
 </div>

app/views/customer/orders/show.html.erb
<div class="container m-5">
  <div class="row">
    <div class="col-1"></div>
    <h4 class="my-4"><span style="background-color:#EFEFEF">　注文履歴詳細　</span></h4>
  </div>


<div class="container">
  <div class="row">
    <table class="table">
      <h5><strong>注文情報</strong></h5>
        <tr>
          <td style="width:15%" class="table-active">注文日</td>
          <td><%= @order.created_at.strftime('%Y/%m/%d') %></td>
        </tr>
        <tr>
          <td class="table-active">配送先</td>
          <td>〒<%= @order.post_code %><br>
             <%= @order.address %><br>
             <%= @order.name %>
          </td>
        </tr>
        <tr>
          <td class="table-active">支払方法</td>
          <td><%= @order.payment_method %></td>
        </tr>
        <tr>
          <td class="table-active">ステータス</td>
          <td><%= @order.state %></td>
        </tr>
    </table>

    <table class="table">
      <h5><strong>注文内容</strong></h5>
      <thead class="table-active">
        <tr>
          <th>商品</th>
          <th>単価（税込）</th>
          <th>個数</th>
          <th>小計</th>
        </tr>
  　　</thead>
        <% @sum = 0 %>
        <% @orderd_items.each do |orderd_item| %>
        <tr>
          <td><%= orderd_item.item.title %></td>
          <td><%= orderd_item.price.to_s(:delimited) %></td>
          <td><%= orderd_item.quantity %></td>
          <!--小計@xと商品合計の計算-->
         <!--１つの商品の価格×数量を計算-->
          <% @x = orderd_item.price * orderd_item.quantity %>
            <!--eachの数だけ@sumに足していく-->
          <% @sum += @x %>
          <td><%= @x.to_s(:delimited) %></td>
        </tr>
        <% end %>
    </table>

    <table class="table">
      <h5><strong>請求情報</state></h5>
        <tr>
          <td style="width:15%" class="table-active">商品合計</td>
          <td><%= @sum.to_s(:delimited) %></td>
        </tr>
        <tr>
          <td class="table-active">配送料</td>
          <td>800</td>
        </tr>
        <tr>
          <td class="table-active"><strong>ご請求額</strong></td>
          <td><%= @order.billing_amount.to_s(:delimited) %></td>
        </tr>
    </table>
  </div>
</div>