config/routes.rb
Rails.application.routes.draw do

  namespace :admin do
    resources :customers, only: [ :index, :show, :edit, :update]
  end

  scope module: :customer do
    resource :customers, only: [ :show, :edit, :update] do
      member do
        patch 'stateupdate'
        get 'exit'
        put "/customers/:id/hide" => "customers#hide", as: 'customers_hide'
      end
    end
  end

  namespace :admin do
    resources :genres, only: [:create, :index, :edit, :update]
  end

  scope module: :customer do
    resources :items, only: [:show, :index]
  end

  namespace :admin do
    resources :items, only: [ :index, :show, :new, :create, :edit, :update]
  end

  scope module: :customer do
      resource :orders, except: [:show] do
        get 'put'
        post 'confirm'
        get 'complete'
    end
    resources :orders, only: [ :index, :show, :create]
  end

  namespace :admin do
    resources :orders, only: [ :index, :show, :update]
  end

  namespace :admin do
    resources :orderd_items, only: [:update]
  end

  scope module: :customer do
    resources :cart_items, only: [:index, :create, :destroy, :update] do
      member do
        delete 'alldestroy'
      end
    end
  end

  scope module: :customer do
    resources :shippings, only: [:create, :destroy, :edit, :update, :index]
  end

  namespace :admin do
    root to: 'homes#top'
  end

  scope module: :customer do
    root to: 'homes#top'
    get 'home/about' => 'homes#about'
  end

      devise_for :admins, controllers: {
    sessions:      'admins/sessions',
    passwords:     'admins/passwords',
    registrations: 'admins/registrations'
  }
  devise_for :customers, controllers: {
    sessions:      'customers/sessions',
    passwords:     'customers/passwords',
    registrations: 'customers/registrations'
  }



end

app/models/customer.rb
class Customer < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  validates :last_name, presence: true
  validates :first_name, presence: true
  validates :kana_last_name, presence: true
  validates :kana_first_name, presence: true
  validates :post_code, presence: true
  validates :post_code, length: { is: 7 }
  validates :address, presence: true
  validates :telephone_number, presence: true

  def update_without_current_password(params, *options)
    params.delete(:current_password)

    if params[:password].blank? && params[:password_confirmation].blank?
      params.delete(:password)
      params.delete(:password_confirmation)
    end

    result = update_attributes(params, *options)
    clean_up_passwords
    result
  end
  has_many :orders, dependent: :destroy
  has_many :cart_items, dependent: :destroy
  has_many :shippings, dependent: :destroy

  def active_for_authentication?
    super && (self.member_state == true)
  end

end

app/controllers/admin/customers_controller.rb
class Admin::CustomersController < ApplicationController

  def index
    @customers = Customer.page(params[:page]).per(10)
  end

  def show
    @customer = Customer.find(params[:id])
  end

  def edit
    @customer = Customer.find(params[:id])
  end

  def update
   @customer = Customer.find(params[:id])
   if @customer.update(customer_params)
    flash[:notice] = "You have updated book successfully."
    redirect_to admin_customer_path(@customer.id)
   else
     render :edit
   end
  end

  private

  def customer_params
    params.require(:customer).permit(:last_name,:first_name, :kana_last_name, :kana_first_name, :post_code, :address, :telephone_number,:telephone_number, :email, :member_state)
  end

end

app/controllers/customer/cart_items_controller.rb
class Customer::CartItemsController < ApplicationController
  before_action :authenticate_customer!

  def index
    @cart_items = current_customer.cart_items
  end

  def create
    @cart_item = CartItem.new(cart_item_params)
    @cart_item.customer_id = current_customer.id
    if @cart_item.save
     redirect_to cart_items_path
    else
     redirect_back(fallback_location: root_path)
    end
  
  end

  def update
    @cart_item = CartItem.find(params[:id])
    @cart_item.update(cart_item_params)
    redirect_to cart_items_path
  end

  def destroy
    @cart_item = CartItem.find(params[:id])
    @cart_item.destroy
    redirect_to cart_items_path
  end

  def alldestroy
    CartItem.destroy_all
    redirect_to cart_items_path
  end

  private

  def cart_item_params
    params.require(:cart_item).permit(:customer_id, :item_id, :amount)
  end
end

app/controllers/customer/customers_controller.rb
class Customer::CustomersController < ApplicationController


  def show
    @customer = current_customer
  end

  def edit
    @customer = current_customer
  end

  def update
    @customer = current_customer
    if @customer.update(customer_params)
     flash[:notice] = "You have updated user successfully."
     redirect_to customers_path
    else
     render :edit
    end
  end

  def exit
    @customer = current_customer
  end

  def hide
    @customer = current_customer
    @customer.update(member_state: false)
    reset_session
    flash[:notice] = "ありがとうございました。またのご利用を心よりお待ちしております。"
    redirect_to root_path
  end


  def active_for_authentication?
    super && (self.member_state == false)
  end

  private

def customer_params
    params.require(:customer).permit(:last_name,:first_name, :kana_last_name, :kana_first_name, :post_code, :address, :telephone_number,:telephone_number, :email)
end

end

app/controllers/customer/homes_controller.rb
class Customer::HomesController < ApplicationController

  def top
    @item = Item.where(sale_state: "true").limit(4).order(" created_at DESC ")
  end
end

app/controllers/customer/items_controller.rb
class Customer::ItemsController < ApplicationController
before_action :authenticate_customer!

  def show
    @item = Item.find(params[:id])
    @cart_item = CartItem.new
  end

  def index
    @items = Item.where(sale_state: "true").limit(8)
    @item = Item.all
    @item_page = Item.page(params[:page]).per(8)
  end
end

app/controllers/customer/orderd_items_controller.rb
class Admin::OrderdItemsController < ApplicationController
  def update
    @orderd_item = OrderdItem.find(params[:id])
    @order = @orderd_item.order
  end
end

app/controllers/customer/orders_controller.rb
class Customer::OrdersController < ApplicationController
  before_action :authenticate_customer!


  def show
    @order = Order.find(params[:id])
    @orderd_items = OrderdItem.where(order_id: params[:id])
    @cart_items = current_customer.cart_items
  end

  def index
    @orders = current_customer.orders

  end

  def put
    @customer = current_customer
    @order_address = current_customer.address
    @order = Order.new
  end

  def confirm
    params[:order][:payment_method] = params[:order][:payment_method].to_i
    @order = Order.new(order_params)

    if params[:order][:address_method] == "0"
      @order.post_code = current_customer.post_code
      @order.address = current_customer.address
      @order.name = current_customer.last_name+current_customer.first_name

    elsif  params[:order][:address_method] ==  "1"
      shipping = Shipping.find(params[:order][:shipping_id])
      @order.post_code = shipping.post_code
      @order.address = shipping.address
      @order.name = shipping.name

    elsif params[:order][:address] ==  "2"
      @order = Shipping.new()
      @order.post_code = params[:order][:post_code]
      @order.shipping_address = params[:order][:shipping_address]
      @order.name = params[:order][:name]
      @order.customer_id = current_customer.id

      if @address.save
      @order.post_code = @shipping_address.post_code
      @order.address = @shipping_address.address
      @order.name = @shipping_address.name

      else
        render 'put'
      end
    end
      @cart_items = CartItem.where(customer_id: current_customer.id)
      @total = 0
  end

    def complete
    end

    def create
      @order = Order.new(order_params)
      @order.customer_id = current_customer.id
      @CartItems = current_customer.cart_items

      if  @order.save
        #orderd_itemsの保存
        current_customer.cart_items.each do |cart_item|
          @orderd_item = OrderdItem.new
          @orderd_item.item_id = cart_item.item_id
          @orderd_item.quantity = cart_item.amount
          @orderd_item.price = (cart_item.item.non_tax_price * 1.1).floor
          @orderd_item.order_id = @order.id  #注文商品に注文idを紐付け
          @orderd_item.save  #注文商品を保存
        end
        current_customer.cart_items.destroy_all
        redirect_to complete_orders_path
      else
        flash[:alert] = "お届け先が正しく入力されていません。お届け先の入力をお願いします。"
        redirect_to  put_orders_path
      end
    end

    private
    def order_params
      params.require(:order).permit(:customer_id, :post_code, :address, :name, :billing_amount, :fee, :payment_method, :state )
    end
end

app/controllers/customer/shippings_controller.rb
class Customer::ShippingsController < ApplicationController


  def create
    @shippings = Shipping.all
    @shipping = Shipping.new(shipping_params)
    @shipping.customer_id = current_customer.id
    if @shipping.save
      flash[:notice] = "Shipping was successfully created"
      redirect_to shippings_path
    else
      render 'index'
    end
  end

  def index
    @shippings = Shipping.all
    @shipping = Shipping.new
    @shipping.customer_id = current_customer.id
  end

  def edit
    @shipping = Shipping.find(params[:id])
  end

  def update
    shipping = Shipping.find(params[:id])
    if shipping.update(shipping_params)
      flash[:notice] = "You have updated shipping successfully."
      redirect_to customers_path
    else
      render 'index'
    end
  end

  def destroy
    shipping = Shipping.find(params[:id])
    shipping.destroy
    redirect_to shippings_path
  end

  private
  def shipping_params
    params.require(:shipping).permit(:post_code, :address, :name)
  end

end

app/controllers/customers/confirmations_controller.rb
# frozen_string_literal: true

class Customers::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/customers/omniauth_callbacks_controller.rb
# frozen_string_literal: true

class Customers::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/heartcombo/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

app/controllers/customers/passwords_controller.rb
# frozen_string_literal: true

class Customers::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/customers/registrations_controller.rb
# frozen_string_literal: true

class Customers::RegistrationsController < Devise::RegistrationsController
  # before_action :configure_sign_up_params, only: [:create]
  before_action :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
  # def create
  #   super
  # end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_up_params
  #   devise_parameter_sanitizer.permit(:sign_up, keys: [:attribute])
  # end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.permit(:account_update, keys: [:attribute])
  # end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end

  def configure_account_update_params
    devise_parameter_sanitizer.permit(:account_update, keys: [:name])
  end

    #必須  更新（編集の反映）時にパスワード入力を省く
  def update_resource(resource, params)
    resource.update_without_password(params)
  end

  #任意  更新後のパスを指定
  def after_update_path_for(resource)
    customers_path(@customer.id)
  end

  def configure_account_update_params
    devise_parameter_sanitizer.permit(:account_update, keys: [:name])
  end


end

app/controllers/customers/sessions_controller.rb
# frozen_string_literal: true

class Customers::SessionsController < Devise::SessionsController
  #before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end

  def reject_customer
    @customer = Customer.find_by(email: params[:customer][:email].downcase)
    if @customer
      if (@customer.valid_password?(params[:customer][:password]) && (@customer.active_for_authentication? == false))
        flash[:error] = "退会済みです。"
        redirect_to new_customer_session_path
      end
    else
      flash[:error] = "必須項目を入力してください。"
    end
  end

end

app/controllers/customers/unlocks_controller.rb
# frozen_string_literal: true

class Customers::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/helpers/admin/customers_helper.rb
module Admin::CustomersHelper
end

app/helpers/customer/cart_items_helper.rb
module Customer::CartItemsHelper
end

app/helpers/customer/customers_helper.rb
module Customer::CustomersHelper
end

app/helpers/customer/homes_helper.rb
module Customer::HomesHelper
end

app/helpers/customer/items_helper.rb
module Customer::ItemsHelper
end

app/views/admin/customers/edit.html.erb
<div class="container m-5">
  <div class="row">
    <div class="col-sm-12 col-md-8 col-lg-1"></div>
    <h4 class="my-4"><span style="background-color:#EFEFEF">　<%= @customer.last_name %><%= @customer.first_name %><%= @customer.first_name %>さんの会員詳細　</span></h4>
  </div>
  <div class="row">
    <div class="col-sm-12 col-md-8 col-lg-1"></div>
    <%= form_for @customer, :url => {action:"update"} do |f| %>
    <table class="table table-borderless">
    <%= flash[:error] %>
      <thead>
        <tr>
          <th style="width:20%">会員ID</th>
          <th style="width:20%"><%= @customer.id %></th>
          <th style="width:65%"></th>
        </tr>
      </thead>
      <tbody>
        <tr>
          <td>氏名</td>
          <td><%= f.text_field :last_name %></td>
          <td><%= f.text_field :first_name %></td>
        </tr>
         <tr>
          <td>フリガナ</td>
          <td><%= f.text_field :kana_last_name %></td>
          <td><%= f.text_field :kana_first_name %></td>
        </tr>
            <tr>
          <td>郵便番号</td>
          <td><%= f.text_field :post_code %></td>
          <td></td>
        </tr>
        <tr>
          <td>住所</td>
          <td><%= f.text_field :address %></td>
          <td></td>
        </tr>
        <tr>
          <td>電話番号</td>
          <td><%= f.text_field :telephone_number %></td>
          <td></td>
        </tr>
          <tr>
          <td>メールアドレス</td>
          <td><%= f.text_field :email %></td>
          <td></td>
        </tr>
        <tr>
          <td><%= f.label :member_state, '会員ステータス' %></td>
          <td><%= f.radio_button :member_state, :true %>有効
              <%= f.radio_button :member_state, :false %>退会
          </td>
          <td></td>
        </tr>
        <tr>
          <td></td>
          <td><%= f.submit "変更を保存", class: "btn btn-success" %></td>
          <td></td>
        </tr>
  </tbody>
</table>
 <% end %>

app/views/admin/customers/index.html.erb
<!--admin-customers-index 顧客一覧画面を表示するため -->
<div class="container m-5">
  <div class="row">
    <div class="col-2"></div>
    <h4 class="my-4 col-2"><span style="background-color:#EFEFEF">　会員一覧　</span></h4>
  </div>
  <div class="row">
    <div class="col-1"></div>
    <table class="table col-10 mx-auto">
      <thead class="thead-light">
        <tr>
          <th>会員ID</th>
          <th>氏名</th>
          <th>メールアドレス</th>
          <th>ステータス</th>
        </tr>
      </thead>
      <tbody>
      <% @customers.each do |customer| %>
        <tr>
          <td><%=  customer.id %></td>
          <td><%= link_to customer.last_name + customer.first_name, admin_customer_path(customer.id) %></td>
          <td><%= customer.email %></td>
            <% if customer.member_state %>
              <td  class="text-success">有効</td>
            <% else %>
              <td>退会</td>
            <% end %>
          </tr>
      <% end %>
      </tbody>
    </table>
  </div>
  <%= paginate @customers %>
<div>

app/views/admin/customers/show.html.erb
<div class="container m-5">
  <div class="row">
    <div class="col-1"></div>
      <h4 class="my-4"><span style="background-color:#EFEFEF">　<%= @customer.last_name + @customer.first_name %>さんの会員詳細　</span></h4>
  </div>
  <div class="row">
    <div class="col-1"></div>
    <table class="table table-borderless">
      <tbody>
        <tr>
          <td style="width:20%">会員ID</td>
          <td style="width:20%"><%= @customer.id %></td>
          <td style="width:65%"></td>
        </tr>
        <tr>
          <td>氏名</td>
          <td><%= @customer.last_name +  @customer.first_name %></td>
        </tr>
        <tr>
          <td>フリガナ</td>
          <td><%= @customer.kana_last_name + @customer.kana_first_name %></td>
        </tr>
        <tr>
          <td>郵便番号</td>
          <td><%= @customer.post_code %></td>
        </tr>
        <tr>
          <td>住所</td>
          <td colspan="2"><%= @customer.address %></td>
        </tr>
        <tr>
          <td>電話番号</td>
          <td><%= @customer.telephone_number %></td>
        </tr>
        <tr>
          <td>メールアドレス</td>
          <td><%= @customer.email %></td>
        </tr>
        <tr>
          <td>会員ステータス</td>
          <% if @customer.member_state %>
            <td class="text-success">有効</td>
          <% else %>
            <td>退会</td>
          <% end %>
        </tr>
        <tr>
          <td></td>
          <td><%= link_to "編集する", edit_admin_customer_path(@customer.id), class: "btn btn-success" %></td>
          <td><div class="text-left"><%= link_to "注文履歴一覧を見る", admin_orders_path(@customer.id), class: "btn btn-primary" %></div></td>
        </tr>
      </tbody>
    </table>
</div>

app/views/admin/customers/update.html.erb
<h1>Admin::Customers#update</h1>
<p>Find me in app/views/admin/customers/update.html.erb</p>