config/routes.rb
Rails.application.routes.draw do

  namespace :admin do
    resources :customers, only: [ :index, :show, :edit, :update]
  end

  scope module: :customer do
    resource :customers, only: [ :show, :edit, :update] do
      member do
        patch 'stateupdate'
        get 'exit'
        put "/customers/:id/hide" => "customers#hide", as: 'customers_hide'
      end
    end
  end

  namespace :admin do
    resources :genres, only: [:create, :index, :edit, :update]
  end

  scope module: :customer do
    resources :items, only: [:show, :index]
  end

  namespace :admin do
    resources :items, only: [ :index, :show, :new, :create, :edit, :update]
  end

  scope module: :customer do
      resource :orders, except: [:show] do
        get 'put'
        post 'confirm'
        get 'complete'
    end
    resources :orders, only: [ :index, :show, :create]
  end

  namespace :admin do
    resources :orders, only: [ :index, :show, :update]
  end

  namespace :admin do
    resources :orderd_items, only: [:update]
  end

  scope module: :customer do
    resources :cart_items, only: [:index, :create, :destroy, :update] do
      member do
        delete 'alldestroy'
      end
    end
  end

  scope module: :customer do
    resources :shippings, only: [:create, :destroy, :edit, :update, :index]
  end

  namespace :admin do
    root to: 'homes#top'
  end

  scope module: :customer do
    root to: 'homes#top'
    get 'home/about' => 'homes#about'
  end

      devise_for :admins, controllers: {
    sessions:      'admins/sessions',
    passwords:     'admins/passwords',
    registrations: 'admins/registrations'
  }
  devise_for :customers, controllers: {
    sessions:      'customers/sessions',
    passwords:     'customers/passwords',
    registrations: 'customers/registrations'
  }



end

app/models/order.rb
class Order < ApplicationRecord
  belongs_to :customer
  has_many :orderd_items, dependent: :destroy

  enum payment_method:[:"クレジットカード", :"銀行振込"]
  enum address_method:[:"ご自身の住所", :"登録済みの住所から選択", :"新しいお届け先"]
  enum state: {"入金待ち": 0, "入金確認": 1, "製作中": 2, "発送準備中": 3, "発送済み": 4}

  # admin/order/showの制作ステータス更新のために記述
  accepts_nested_attributes_for :orderd_items

  validates :post_code, presence: true
  validates :post_code, length:{ is: 7 }
  validates :address, presence: true
  validates :name, presence: true

end

app/controllers/admin/orders_controller.rb
class Admin::OrdersController < ApplicationController
  before_action :authenticate_admin!

  def index
    @orders = Order.all
    @orderd_items = OrderdItem.where(order_id: params[:id])
  end

  def show
		@order = Order.find(params[:id])
    #show.html内でorderd_item(中間テーブル)を呼び出すために使用する
		@orderd_items = OrderdItem.where(order_id: params[:id])
  end

  def update
    @order = Order.find(params[:id])
    @order.update(order_params)
    redirect_back(fallback_location: root_path)
  end

  private
  # show.htmlにてorderd_itemの制作ステータスを更新できるようにするため、rderd_item_attributes: [:create_state] を記述しています
  def order_params
    params.require(:order).permit(:state, orderd_item_attributes:[:id, :create_state])
  end
end

app/controllers/customer/orders_controller.rb
class Customer::OrdersController < ApplicationController
  before_action :authenticate_customer!


  def show
    @order = Order.find(params[:id])
    @orderd_items = OrderdItem.where(order_id: params[:id])
    @cart_items = current_customer.cart_items
  end

  def index
    @orders = current_customer.orders

  end

  def put
    @customer = current_customer
    @order_address = current_customer.address
    @order = Order.new
  end

  def confirm
    params[:order][:payment_method] = params[:order][:payment_method].to_i
    @order = Order.new(order_params)

    if params[:order][:address_method] == "0"
      @order.post_code = current_customer.post_code
      @order.address = current_customer.address
      @order.name = current_customer.last_name+current_customer.first_name

    elsif  params[:order][:address_method] ==  "1"
      shipping = Shipping.find(params[:order][:shipping_id])
      @order.post_code = shipping.post_code
      @order.address = shipping.address
      @order.name = shipping.name

    elsif params[:order][:address] ==  "2"
      @order = Shipping.new()
      @order.post_code = params[:order][:post_code]
      @order.shipping_address = params[:order][:shipping_address]
      @order.name = params[:order][:name]
      @order.customer_id = current_customer.id

      if @address.save
      @order.post_code = @shipping_address.post_code
      @order.address = @shipping_address.address
      @order.name = @shipping_address.name

      else
        render 'put'
      end
    end
      @cart_items = CartItem.where(customer_id: current_customer.id)
      @total = 0
  end

    def complete
    end

    def create
      @order = Order.new(order_params)
      @order.customer_id = current_customer.id
      @CartItems = current_customer.cart_items

      if  @order.save
        #orderd_itemsの保存
        current_customer.cart_items.each do |cart_item|
          @orderd_item = OrderdItem.new
          @orderd_item.item_id = cart_item.item_id
          @orderd_item.quantity = cart_item.amount
          @orderd_item.price = (cart_item.item.non_tax_price * 1.1).floor
          @orderd_item.order_id = @order.id  #注文商品に注文idを紐付け
          @orderd_item.save  #注文商品を保存
        end
        current_customer.cart_items.destroy_all
        redirect_to complete_orders_path
      else
        flash[:alert] = "お届け先が正しく入力されていません。お届け先の入力をお願いします。"
        redirect_to  put_orders_path
      end
    end

    private
    def order_params
      params.require(:order).permit(:customer_id, :post_code, :address, :name, :billing_amount, :fee, :payment_method, :state )
    end
end

app/helpers/admin/orders_helper.rb
module Admin::OrdersHelper
end

app/helpers/customer/orders_helper.rb
module Customer::OrdersHelper
end

app/views/admin/orders/index.html.erb
<h1>注文履歴一覧</h1>
<div class="container m-5">
  <div class="row">
    <div class="col-sm-12 col-md-8 col-lg-2"></div>
    <h4 class="my-4 "><span style="background-color:#EFEFEF">　注文履歴一覧　</span></h4>
  </div>
  <table class="table col-7 mx-auto">
    <thead class="thead-light">
      <tr>
        <th>購入日時</th>
        <th>購入者</th>
        <th>注文個数</th>
        <th>注文ステータス</th>
        <th>注文詳細</th>
      </tr>
    </thead>
    <tbody>
    <% @orders.each do |order| %>
      <tr>
        <td><%= order.customer.created_at.strftime("%Y-%m-%d %H:%M") %></td>
        <td><%= order.name %></td>
        <td>
          <% @sum = 0 %>
          <% order.orderd_items.each do |orderd_item| %>
          <!--１つの商品の数量を計算-->
          <% @x = orderd_item.quantity %>
          <!--eachの数だけ@sumに足していく-->
          <% @sum += @x %>
          <% end %>
          <!--表示するのは1つの@sumの中身-->
          <%= @sum %>
        </td>
        <td><%= order.state %></td>
        <td><%= link_to '詳細画面へ', admin_order_path(order), class: "btn btn-info" %></td>
      </tr>
    <% end %>
    </tbody>
  </table>
<div>

app/views/admin/orders/show.html.erb
<div class="container m-5">
  <div class="row">
    <div class="col-1"></div>
    <h4 class="my-4"><span style="background-color:#EFEFEF">　注文履歴詳細　</span></h4>
  </div>
      <table class=table>
        <tr>
          <th>購入者</th>
          <th><%= @order.customer.last_name + @order.customer.first_name %></th>
        <tr>
          <th>注文日</th>
          <th><%= @order.created_at %></th>
        </tr>
        <tr>
        <tr>
          <th>配送先</th>
          <th>
            <%= @order.post_code %>
            <%= @order.address %>
            <%= @order.name %>
          </th>
        </tr>
        <tr>
          <th>支払方法</th>
          <th><%= @order.payment_method %></th>
        </tr>
        <tr>
          <th>注文ステータス</th>
          <th>
            <%= form_for @order, :url => { action: "update" } do |f| %>
            <%= f.select :state, ['入金待ち', '入金確認', '製作中', '発送準備中', '発送済み'] %>
            <%= f.submit "更新", class:'btn btn-success' %>
            <% end %>
        </tr>
      </table>

    <div class="row">
      <table class="table col-7">
        <thead class="thead-light">
          <tr>
            <th>商品名</th>
            <th>単価(税込)</th>
            <th>数量</th>
            <th>小計</th>
            <th>制作ステータス</th>
            <th></th>
          </tr>
        </thead>
        <tbody>
            <!--商品中間テーブルのカラムを呼び出してます-->
            <% @sum = 0 %>
            <% @orderd_items.each do |orderd_item| %>
              <tr>
                <td><%= orderd_item.item.title %></td>
                <td><%= orderd_item.price.to_s(:delimited) %></td>
                <td><%= orderd_item.quantity %></td>
                <!--小計@xと商品合計@sumの計算-->
                <!--１つの商品の価格×数量を計算-->
                <% @x = orderd_item.price * orderd_item.quantity %>
                <!--eachの数だけ@sumに足していく-->
                <% @sum += @x %>
                <td><%= @x.to_s(:delimited) %></td>
                <td>
                  <%= form_for orderd_item, url: admin_orderd_item_path(orderd_item) do |f| %>
                  <%= f.select :create_state, ['着手不可', '制作待ち', '制作中', '制作完了'] %>
                  <td><%= f.submit "更新", class:'btn btn-success' %></td>
                  <% end %>
                </td>
              </tr>
            <% end %>
          </tbody>
        </table>
      <table class="col-3  align-self-end offset-1">
        <tr>
          <th>商品合計</th>
          <th><%= @sum.to_s(:delimited) %></th>
        </tr>
        <tr>
          <th>送料</th>git checkout develop 
          <th>800</th>
        </tr>
        <tr>
          <th>請求合計金額</th>
          <th><%= @order.billing_amount.to_s(:delimited) %></th>
        </tr>
      </table>
    </div>
    </div>
  </div>